version: "3.9"
services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: arbaz@51
      MYSQL_DATABASE: emailsaas
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: backend
    restart: always
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - mysql

  smtp:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    command: node src/smtp/smtpServer.js
    depends_on:
      - backend

volumes:
  mysql_data:
