version: "3.9"
services:
  mysql:
    image: mysql:8
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: arbaz@51
      MYSQL_DATABASE: emailsaas
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mysql

  smtp:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && node src/smtp/server.js"
    container_name: smtp-server
    ports:
      - "587:587"
    env_file:
      - .env
    depends_on:
      - backend

  prisma-studio:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npx prisma studio"
    container_name: prisma
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - mysql

volumes:
  mysql_data:
